language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t edlalo/fib-client-tests -f ./fib-client/Dockerfile.dev ./fib-client

script:
  - docker run -e CI=true edlalo/fib-client-tests yarn test --coverage

after_success:
  - docker build -t edlalo/multi-fib-client ./fib-client
  - docker build -t edlalo/multi-nginx ./nginx
  - docker build -t edlalo/multi-redis-worker ./redis-worker
  - docker build -t edlalo/multi-server ./server
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login docker.io -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push -t edlalo/multi-fib-client ./fib-client
  - docker push -t edlalo/multi-nginx ./nginx
  - docker push -t edlalo/multi-redis-worker ./redis-worker
  - docker push -t edlalo/multi-server ./server
