language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t lalo/react-test -f ./fib-client/Dockerfile.for.travis.dev .

script:
  - docker run -e CI=true lalo/react-test yarn test --coverage

after_success:
  - docker build -t lalo/multi-fib-client ./fib-client
  - docker build -t lalo/multi-nginx ./nginx
  - docker build -t lalo/multi-redis-worker ./redis-worker
  - docker build -t lalo/multi-server ./server
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push lalo/multi-fib-client
  - docker push lalo/multi-nginx
  - docker push lalo/multi-redis-worker
  - docker push lalo/multi-server
